### PR TITLE
add post about opening previous buffer with ctrl-o

### PR DESCRIPTION
**Pull request by thebadmonkeydev**
This blew my mind when I found this one out.  Would love some feedback on language style, but I've got a million of these that I'd love to share.

### CODE REVIEW

**Comment by cbartlett** [comment]
Do you want to expand it slightly to include Control-I which jumps back forward? There's a plethora that could be written on jumps in general: http://vim.wikia.com/wiki/Jumping_to_previously_visited_locations

**Comment by thebadmonkeydev** [comment]
working on a re-write right now that expands on the jumps topic further.  I'll push changes here later today.

**Comment by thebadmonkeydev** [comment]
Just pushed a re-write commit. let me know what you think.

**Comment by cbartlett** [comment]
🎈 thanks!

**Pull request merged**
